catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - undici-types@6.21.0
  - chokidar@4.0.3

packages:
  - apps/*

catalogs:
  backend:
    '@aws-sdk/client-s3': ^3.962.0
    '@faker-js/faker': ^10.1.0
    '@fastify/cookie': ^11.0.2
    '@fastify/multipart': ^9.3.0
    '@fastify/session': ^11.1.1
    '@fastify/static': ^9.0.0
    '@nestjs/axios': ^4.0.1
    '@nestjs/cli': ^11.0.14
    '@nestjs/common': ^11.1.11
    '@nestjs/config': ^4.0.2
    '@nestjs/core': ^11.1.11
    '@nestjs/mapped-types': ^2.1.0
    '@nestjs/platform-express': ^11.1.11
    '@nestjs/platform-fastify': ^11.1.11
    '@nestjs/schematics': ^11.0.9
    '@nestjs/swagger': ^11.2.3
    '@nestjs/terminus': ^11.0.0
    '@nestjs/testing': ^11.1.11
    '@prisma/adapter-pg': ^7.2.0
    '@prisma/client': ^7.2.0
    '@swc/cli': ^0.7.9
    '@swc/core': ^1.15.8
    '@types/bcrypt': ^6.0.0
    '@types/express': ^5.0.6
    '@types/pg': ^8.16.0
    axios: ^1.13.2
    bcrypt: ^6.0.0
    class-transformer: ^0.5.1
    class-validator: ^0.14.3
    date-fns: ^4.1.0
    dotenv: ^17.2.3
    fastify: ^5.6.2
    ioredis: ^5.8.2
    joi: ^18.0.2
    json-schema-faker: ^0.5.9
    pg: ^8.16.3
    prisma: ^7.2.0
    reflect-metadata: ^0.2.2
    resend: ^6.6.0
    rxjs: ^7.8.2
    source-map-support: ^0.5.21
    ts-loader: ^9.5.4
    tsconfig-paths: ^4.2.0
    tsdown: ^0.18.4
    type-fest: ^5.3.1
    winston: ^3.19.0
    winston-daily-rotate-file: ^5.0.0
  frontend:
    '@tailwindcss/vite': ^4.1.18
    '@tanstack/vue-table': ^8.21.3
    '@types/lodash-es': ^4.17.12
    '@vee-validate/zod': ^4.15.1
    '@vitejs/plugin-vue': ^6.0.3
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': ^14.1.0
    '@vueuse/router': ^14.1.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cropperjs: ^2.1.0
    dayjs: ^1.11.19
    ky: ^1.14.2
    lodash-es: ^4.17.22
    lucide-vue-next: ^0.562.0
    monaco-editor: 0.50.0
    nanoid: ^5.1.6
    pinia: ^3.0.4
    pinia-plugin-persistedstate: ^4.7.1
    reka-ui: ^2.7.0
    rollup-plugin-visualizer: ^6.0.5
    shiki: ^3.20.0
    swrv: ^1.1.0
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.18
    tw-animate-css: ^1.4.0
    uuid: ^13.0.0
    vee-validate: ^4.15.1
    vite: ^7.3.0
    vite-plugin-compression2: ^2.4.0
    vite-plugin-monaco-editor-esm: ^2.0.2
    vue: ^3.5.26
    vue-picture-cropper: ^0.7.0
    vue-router: ^4.6.4
    vue-sonner: ^2.0.9
    vue-tsc: ^3.2.1
    zod: '3'
  public:
    '@antfu/eslint-config': ^6.7.3
    '@types/node': ^25.0.3
    eslint: ^9.39.2
    tsx: ^4.21.0
    typescript: ^5.9.3

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - esbuild
  - prisma
  - vue-demi
