export const roles = [
  // 团队角色
  {
    name: 'team:owner',
    description: '团队所有者',
    type: 'TEAM',
    permissions: [
      'team:read',
      'team:write',
      'team:admin',
      'team:member:invite',
      'team:member:remove',
      'team:member:manage',
      'project:read',
      'project:write',
      'project:admin',
      'project:create',
      'project:member:invite',
      'project:member:remove',
      'project:member:manage',
      'api:read',
      'api:write',
      'api:create',
      'api:delete',
      'api:publish',
      'api:version:manage',
      'api:mock:manage',
      'api:test',
      'api_group:read',
      'api_group:write',
      'api_group:create',
      'api_group:delete',
    ],
  },
  {
    name: 'team:admin',
    description: '团队管理员',
    type: 'TEAM',
    permissions: [
      'team:read',
      'team:write',
      'team:admin',
      'team:member:invite',
      'team:member:remove',
      'team:member:manage',
      'project:read',
      'project:write',
      'project:create',
      'project:member:invite',
      'project:member:remove',
      'project:member:manage',
      'api:read',
      'api:write',
      'api:create',
      'api:delete',
      'api:publish',
      'api:version:manage',
      'api:mock:manage',
      'api:test',
      'api_group:read',
      'api_group:write',
      'api_group:create',
      'api_group:delete',
    ],
  },
  {
    name: 'team:member',
    description: '团队成员',
    type: 'TEAM',
    permissions: [
      'team:read',
      'project:read',
      'project:create',
      'api:read',
      'api:write',
      'api:create',
      'api:mock:manage',
      'api:test',
      'api_group:read',
      'api_group:write',
      'api_group:create',
    ],
  },
  {
    name: 'team:guest',
    description: '团队访客',
    type: 'TEAM',
    permissions: [
      'team:read',
      'project:read',
      'api:read',
      'api:test',
      'api_group:read',
    ],
  },

  // 项目角色
  {
    name: 'project:admin',
    description: '项目管理员',
    type: 'PROJECT',
    permissions: [
      'project:read',
      'project:write',
      'project:admin',
      'project:member:invite',
      'project:member:remove',
      'project:member:manage',
      'api:read',
      'api:write',
      'api:create',
      'api:delete',
      'api:publish',
      'api:version:manage',
      'api:mock:manage',
      'api:test',
      'api_group:read',
      'api_group:write',
      'api_group:create',
      'api_group:delete',
    ],
  },
  {
    name: 'project:editor',
    description: '项目编辑者',
    type: 'PROJECT',
    permissions: [
      'project:read',
      'project:write',
      'api:read',
      'api:write',
      'api:create',
      'api:publish',
      'api:version:manage',
      'api:mock:manage',
      'api:test',
      'api_group:read',
      'api_group:write',
      'api_group:create',
    ],
  },
  {
    name: 'project:viewer',
    description: '项目查看者',
    type: 'PROJECT',
    permissions: [
      'project:read',
      'api:read',
      'api:test',
      'api_group:read',
    ],
  },
] as const

export type RoleType = (typeof roles)[number]['name']

export enum RoleName {
  TEAM_OWNER = 'team:owner',
  TEAM_ADMIN = 'team:admin',
  TEAM_MEMBER = 'team:member',
  TEAM_GUEST = 'team:guest',
  PROJECT_ADMIN = 'project:admin',
  PROJECT_EDITOR = 'project:editor',
  PROJECT_VIEWER = 'project:viewer',
}

export const ROLE_CATEGORIES = ['TEAM', 'PROJECT', 'SYSTEM'] as const

export type RoleCategory = (typeof ROLE_CATEGORIES)[number]
