export enum ErrorCode {
  /** 用户不存在 */
  USER_NOT_FOUND = 10001,
  /** 用户已存在 */
  USER_ALREADY_EXISTS = 10002,
  /** 密码错误 */
  INVALID_PASSWORD = 10003,
  /** 邮箱格式不正确 */
  INVALID_EMAIL = 10004,
  /** 邮箱已被注册 */
  EMAIL_ALREADY_REGISTERED = 10005,
  /** 用户名格式不正确 */
  INVALID_USERNAME = 10006,
  /** 用户名已被占用 */
  USERNAME_ALREADY_EXISTS = 10007,
  /** 账号被禁用 */
  ACCOUNT_DISABLED = 10008,
  /** 账号被锁定 */
  ACCOUNT_LOCKED = 10009,
  /** 验证码错误或已过期 */
  INVALID_VERIFICATION_CODE = 10010,
  /** 两次密码输入不一致 */
  PASSWORD_MISMATCH = 10011,
  /** Session已过期或无效 */
  SESSION_EXPIRED = 10012,
  /** 无权限操作此Session */
  SESSION_FORBIDDEN = 10013,

  /** 权限不足 */
  INSUFFICIENT_PERMISSIONS = 20001,
  /** 角色不存在 */
  ROLE_NOT_FOUND = 20002,
  /** 权限不存在 */
  PERMISSION_NOT_FOUND = 20003,
  /** 角色名称已存在 */
  ROLE_NAME_EXISTS = 20004,
  /** 权限名称已存在 */
  PERMISSION_NAME_EXISTS = 20005,
  /** 系统角色不能删除 */
  SYSTEM_ROLE_CANNOT_DELETE = 20006,

  /** 团队不存在 */
  TEAM_NOT_FOUND = 30001,
  /** 团队名称已存在 */
  TEAM_NAME_EXISTS = 30002,
  /** 团队标识符已存在 */
  TEAM_SLUG_EXISTS = 30003,
  /** 不是团队成员 */
  NOT_TEAM_MEMBER = 30004,
  /** 团队成员不存在 */
  TEAM_MEMBER_NOT_FOUND = 30005,
  /** 用户已是团队成员 */
  USER_ALREADY_TEAM_MEMBER = 30006,
  /** 不能移除团队所有者 */
  CANNOT_REMOVE_TEAM_OWNER = 30007,
  /** 不能删除有项目的团队 */
  CANNOT_DELETE_TEAM_WITH_PROJECTS = 30008,
  /** 团队已被禁用 */
  TEAM_DISABLED = 30009,
  /** 不能修改团队所有者角色 */
  CANNOT_MODIFY_OWNER_ROLE = 30010,
  /** 团队成员数量已达上限 */
  TEAM_MEMBER_LIMIT_EXCEEDED = 30011,

  /** 项目不存在 */
  PROJECT_NOT_FOUND = 40001,
  /** 项目名称已存在 */
  PROJECT_NAME_EXISTS = 40002,
  /** 项目标识符已存在 */
  PROJECT_SLUG_EXISTS = 40003,
  /** 不是项目成员 */
  NOT_PROJECT_MEMBER = 40004,
  /** 项目成员不存在 */
  PROJECT_MEMBER_NOT_FOUND = 40005,
  /** 用户已是项目成员 */
  USER_ALREADY_PROJECT_MEMBER = 40006,
  /** 不能删除包含 API 的项目 */
  CANNOT_DELETE_PROJECT_WITH_APIS = 40007,
  /** 项目已被删除 */
  PROJECT_DELETED = 40008,
  /** 不能移除项目的最后一个管理员 */
  CANNOT_REMOVE_LAST_ADMIN = 40009,
  /** 环境名称已存在 */
  ENVIRONMENT_NAME_EXISTS = 40010,
  /** 环境不存在 */
  ENVIRONMENT_NOT_FOUND = 40011,
  /** 不能删除项目的最后一个环境 */
  CANNOT_DELETE_LAST_ENVIRONMENT = 40012,
  /** 用户不是团队成员 */
  USER_NOT_TEAM_MEMBER = 40013,

  /** API 分组不存在 */
  API_GROUP_NOT_FOUND = 50001,

  /** 参数错误 */
  INVALID_PARAMS = 90001,
  /** 系统内部错误 */
  INTERNAL_SERVER_ERROR = 99999,
}
